version: '3'

services:
  env_ore:
    image: env_ore:${ORE_TAG}
    build:
      context: ../
      dockerfile: Docker/Dockerfile-ORE
      args:
        - quantlib_version=${QL_TAG}
        - num_cores=${NUM_CORES}
